version: 1

script:
  # https://github.com/AppImageCrafters/appimage-builder/issues/271
  - which mksquashfs || apt install -y --no-install-recommends squashfs-tools

AppDir:
  path: /home/runner/work/far2l/far2l/AppDir/

  app_info:
    id: io.github.elfmz.far2l
    name: far2l
    icon: far2l
    version: "{{APPIMAGE_VERSION}}"
    exec: usr/bin/far2l
    exec_args: $@

  apt:
    arch: "{{APPIMAGE_APT_ARCH}}"
    allow_unauthenticated: true
    sources:
      - sourceline: deb http://archive.ubuntu.com/ubuntu/ "{{APPIMAGE_APT_DISTRO}}" main restricted universe multiverse
      - sourceline: deb http://archive.ubuntu.com/ubuntu/ "{{APPIMAGE_APT_DISTRO}}"-updates main restricted universe multiverse
      - sourceline: deb http://security.ubuntu.com/ubuntu/ "{{APPIMAGE_APT_DISTRO}}"-security main restricted universe multiverse
    include:
      - libarchive13
      - libneon27
      - libnfs13
      - libpcre3
      - libsmbclient
      - libuchardet0
      - libwxgtk3.0-gtk3-0v5
      - libxerces-c3.2
      - libxi6
    exclude:
      - adwaita-icon-theme
      - hicolor-icon-theme
      - humanity-icon-theme
      - dbus-user-session
      - dconf-service
      - glib-networking-services
      - gsettings-desktop-schemas
      - libavahi-client3
      - libavahi-common3
      - libcolord2
      - libcups2
      - libdb5.3
      - libdconf1
      - libfontconfig1
      - libgdk-pixbuf2.0-0
      - libgmp10
      - libgnutls30
      - libgssapi-krb5-2
      - libhogweed5
      - libicu66
      - libjson-glib-1.0-0
      - libk5crypto3
      - libkrb5-3
      - libkrb5support0
      - liblcms2-2
      - libncursesw6
      - libnettle7
      - libp11-kit0
      - libpsl5
      - librest-0.7-0
      - libsoup-gnome2.4-1
      - libsoup2.4-1
      - libsqlite3-0
      - libtasn1-6
      - libthai-data
      - libtiff5
      - libtinfo6
      - libunistring2
      - libwebp6
      - libxml2
      - mime-support
      - python3
      - python3-minimal
      - readline-common
      - systemd
      - systemd-timesyncd
      - tzdata
      - xkb-data

  files:
    exclude:
      - usr/share/man
      - usr/share/doc*

AppImage:
  arch: "{{APPIMAGE_ARCH}}"
  update-information: "gh-releases-zsync|spvkgn|far2l|latest|far2l-*-{{APPIMAGE_ARCH}}.AppImage.zsync"
