version: 1

script:
  # https://github.com/AppImageCrafters/appimage-builder/issues/271
  - which mksquashfs || apt install -y --no-install-recommends squashfs-tools

AppDir:
  path: /home/runner/work/far2l/far2l/AppDir/
  app_info:
    id: io.github.elfmz.far2l
    name: far2l
    icon: far2l
    version: "{{APPIMAGE_VERSION}}"
    exec: usr/bin/far2l
    exec_args: $@
  apt:
    arch: "{{APPIMAGE_APT_ARCH}}"
    allow_unauthenticated: true
    sources:
      - sourceline: deb http://archive.ubuntu.com/ubuntu/ "{{APPIMAGE_APT_DISTRO}}" main restricted universe multiverse
      - sourceline: deb http://archive.ubuntu.com/ubuntu/ "{{APPIMAGE_APT_DISTRO}}"-updates main restricted universe multiverse
      - sourceline: deb http://security.ubuntu.com/ubuntu/ "{{APPIMAGE_APT_DISTRO}}"-security main restricted universe multiverse
    include:
      - libarchive13
      - libneon27
      - libnfs13
      - libpcre3
      - libsmbclient
      - libuchardet0
      - libwxgtk3.0-gtk3-0v5
      - libxerces-c3.2
      - libxi6
    exclude:
      - adwaita-icon-theme
      - humanity-icon-theme
      - dbus
      - libgdk-pixbuf2.0-0
      - tzdata
      - libthai-data

  files:
    exclude:
      - usr/share/man
      - usr/share/doc*
      - usr/share/glib-2.0
      - usr/share/X11

AppImage:
  arch: "{{APPIMAGE_ARCH}}"
  update-information: "gh-releases-zsync|spvkgn|far2l|latest|far2l-*-{{APPIMAGE_ARCH}}.AppImage.zsync"
