#!/bin/sh

export APPIMAGE="$(readlink -f "${0}")"
export APPDIR="$(dirname "${APPIMAGE}")"

export LD_LIBRARY_PATH="${APPDIR}/usr/lib/:${LD_LIBRARY_PATH}"
export PATH="${APPDIR}/usr/bin:${PATH}"

exec "${APPDIR}/usr/bin/@APP@" "$@"
